import * as vscode from 'vscode';

/**
 * Helpers for changes generated by VS Code automatic indentation.
 * These changes should not advance Fake Type's preset cursor.
 */
export function isLikelyAutoIndentChange(change: vscode.TextDocumentContentChangeEvent): boolean {
    const text = change.text;

    if (!text.includes('\n')) {
        return false;
    }

    const afterNewline = text.split(/\r?\n/).pop() ?? '';
    return afterNewline.length > 0 && /^[\t ]+$/.test(afterNewline);
}

export function shouldUseRawInsert(text: string): boolean {
    return text === '\n' || text === '\r\n' || text === '\t';
}
